<?php

namespace App\Entity;

use App\Repository\JoueurRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\Encoder\EncoderAwareInterface;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=JoueurRepository::class)
 * @UniqueEntity(fields="email", message="Sorry, this email address is already in use.", groups={"admin","joueur","user"})
 */
class Joueur extends User
{
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups({"profile"})
     */
    private $Nom;

    /**
     * @Groups({"profile"})
     * @ORM\ManyToOne(targetEntity=Equipe::class, inversedBy="joueurs")
     */
    private $equipe;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $score = 0;

    /**
     * @ORM\ManyToOne(targetEntity=Admin::class, inversedBy="joueurs")
     */
    private $owner;

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(?string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function __construct()
    {
        $this->password = 'change_me';
        $this->roles = ['ROLE_USER'];
    }

    public function getEquipe(): ?Equipe
    {
        return $this->equipe;
    }

    public function setEquipe(?Equipe $equipe): self
    {
        $this->equipe = $equipe;
        return $this;
    }


    public function setPassword(String $password): User
    {
        return parent::setPassword('change_me'); // TODO: Change the autogenerated stub
    }

    public function getId(): ?int
    {
        return parent::getId(); // TODO: Change the autogenerated stub
    }

    public function __toString()
    {
        return $this->email;
        // TODO: Implement __toString() method.
    }

    public function getScore(): ?int
    {
        return $this->score;
    }

    public function setScore(?int $score): self
    {
        $this->score = $score;

        return $this;
    }

    public function getOwner(): ?Admin
    {
        return $this->owner;
    }

    public function setOwner(?Admin $owner): self
    {
        $this->owner = $owner;

        return $this;
    }

}
